
MACRO(VISIT_INSTALL_TARGETS)    
  INSTALL(TARGETS ${ARGN}
    DESTINATION bin
    COMPONENT Runtime)              
ENDMACRO(VISIT_INSTALL_TARGETS)


FUNCTION(ADD_VISIT_STMDREADER NAME VERSION)
SET(PLUGIN_NAME "vtk${NAME}")
SET(PLUGIN_VERSION "${VERSION}")
SET(ARG_VISIT_READER_NAME)
SET(ARG_VISIT_READER_FILE_PATTERN)

PV_PLUGIN_PARSE_ARGUMENTS(ARG 
  "VISIT_READER_NAME;VISIT_READER_FILE_PATTERN"
    "" ${ARGN} )

INCLUDE_DIRECTORIES(
${CMAKE_CURRENT_BINARY_DIR}
${CMAKE_CURRENT_SOURCE_DIR}
${AVTALGORITHMS_BINARY_DIR}
${AVTALGORITHMS_SOURCE_DIR}
${VISIT_COMMON_INCLUDES}
${VISIT_SOURCE_DIR}/include
${AVT_DATABASE_SOURCE_DIR}/Database
${AVT_DATABASE_SOURCE_DIR}/Ghost
${AVT_DATABASE_SOURCE_DIR}/Formats
${AVT_DBATTS_SOURCE_DIR}/MetaData
${AVT_DBATTS_SOURCE_DIR}/SIL
${VISIT_SOURCE_DIR}/avt/Math
${VISIT_SOURCE_DIR}/avt/VisWindow/VisWindow
${AVT_PIPELINE_SOURCE_DIR}/AbstractFilters
${AVT_PIPELINE_SOURCE_DIR}/Data
${AVT_PIPELINE_SOURCE_DIR}/Pipeline
${AVT_PIPELINE_SOURCE_DIR}/Sinks
${AVT_PIPELINE_SOURCE_DIR}/Sources
${VTK_INCLUDE_DIRS}
)

#need to insert in the auto generated VTK class
#as  ${SERVER_SOURCES}
CONFIGURE_FILE(
  ${VISIT_CMAKE_DIR}/VisItSTMD.h.in
  ${CMAKE_CURRENT_BINARY_DIR}/${PLUGIN_NAME}.h @ONLY)
  
CONFIGURE_FILE(
  ${VISIT_CMAKE_DIR}/VisItSTMD.cxx.in
  ${CMAKE_CURRENT_BINARY_DIR}/${PLUGIN_NAME}.cxx @ONLY)

SET (vtk_reader_sources
      ${CMAKE_CURRENT_BINARY_DIR}/${PLUGIN_NAME}.cxx
      ${CMAKE_CURRENT_BINARY_DIR}/${PLUGIN_NAME}.h
    )  

LIST(APPEND ARGN "SERVER_MANAGER_SOURCES;${vtk_reader_sources}")
MESSAGE(STATUS "ARGN: ${ARGN}")

#now we need to add the XML info

ADD_PARAVIEW_PLUGIN( ${NAME} ${VERSION} ${ARGN} )


ENDFUNCTION(ADD_VISIT_STMDREADER)