
MACRO(VISIT_INSTALL_TARGETS)    
  INSTALL(TARGETS ${ARGN}
    DESTINATION bin
    COMPONENT Runtime)              
ENDMACRO(VISIT_INSTALL_TARGETS)

#set up LIBRARY_OUTPUT_PATH
set(LIBRARY_OUTPUT_PATH ${VISIT_BINARY_DIR}/bin ) 